### ISSUE TITLE
Code font doesn't render underscore ("_")

### ISSUE THREAD

**Issue by phryk** [kidscancode/godot_recipes#7]
First of all, thanks for the nice resources, but I've noticed that underscores ("_") don't render in the code blocks on site:

![underscore](https://user-images.githubusercontent.com/1021513/92037998-fe7ed100-ed72-11ea-9675-7951b4011379.png)

I traced this to theme.css, line 649 setting line-height for `<pre>` elements to 1.15. Setting this to 1.2 alleviates the problem, at least for me. (:

**Comment by cbscribe** [comment]
Should be fixed now, at least from my testing.

**Comment by phryk** [comment]
Still broken for me, tho I did also find a place where *some* but not all underscores within a code block are now rendered: 

http://kidscancode.org/godot_recipes/2d/2d_shooting/
![under](https://user-images.githubusercontent.com/1021513/92793864-1b3c8980-f3af-11ea-90c7-12f7735732ef.png)

This is on firefox – I've also just tested on chromium and am not seeing any underscores there…
Im running FreeBSD, but I'm somewhat sure that's not the issue, as I haven't had any such issues before, but currently don't have another OS to put that to the test.
